name: haminfo
recipe: drupal11
config:
  webroot: web
  xdebug: true

services:
  appserver:
    config:
      php: lando-config/php.ini
  node:
    type: node:20
  database:
    type: mysql:8.0

tooling:
  npm:
    service: node
    cmd: npm

  theme-install:
    service: node
    dir: /app/web/themes/custom/haminfo
    cmd: npm install

  theme-build:
    service: node
    dir: /app/web/themes/custom/haminfo
    cmd: npm run production

  theme-watch:
    service: node
    dir: /app/web/themes/custom/haminfo
    cmd: npm run watch
